/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * FXTradeRestController as REST API
 *
 * <p>Exposes REST endpoints for the FXTrade entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	FXTradeBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateFXTradeCommand</li>
 *      <li></li>UpdateFXTradeCommand</li>
 *      <liDeleteFXTradeCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/FXTrade")
public class FXTradeRestController extends BaseSpringRestController {

    /**
     * Handles create a FXTrade.  if not key provided, calls create, otherwise calls save
     * @param		FXTrade	fXTrade
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateFXTradeCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = FXTradeBusinessDelegate.getFXTradeInstance().createFXTrade( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a FXTrade.  if no key provided, calls create, otherwise calls save
     * @param		FXTrade fXTrade
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateFXTradeCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateFXTradeCommand
			// -----------------------------------------------
			completableFuture = FXTradeBusinessDelegate.getFXTradeInstance().updateFXTrade(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "FXTradeController:update() - successfully update FXTrade - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a FXTrade entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteFXTradeCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	FXTradeBusinessDelegate delegate = FXTradeBusinessDelegate.getFXTradeInstance();

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted FXTrade with key " + command.getFXTradeId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a FXTrade using a UUID
     * @param		UUID uuid 
     * @return		FXTrade
     */    
    @GetMapping("/load")
    public FXTrade load( @RequestParam(required=true) UUID uuid ) {    	
    	FXTrade entity = null;

    	try {  
    		entity = FXTradeBusinessDelegate.getFXTradeInstance().getFXTrade( new FXTradeFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load FXTrade using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all FXTrade business objects
     * @return		Set<FXTrade>
     */
    @GetMapping("/")
    public List<FXTrade> loadAll() {                
    	List<FXTrade> fXTradeList = null;
        
    	try {
            // load the FXTrade
            fXTradeList = FXTradeBusinessDelegate.getFXTradeInstance().getAllFXTrade();
            
            if ( fXTradeList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all FXTrades" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all FXTrades ", exc );
        	return null;
        }

        return fXTradeList;
                            
    }

    /**
     * save Customer on FXTrade
     * @param		command AssignCustomerToFXTradeCommand
     */     
	@PutMapping("/assignCustomer")
	public void assignCustomer( @RequestBody AssignCustomerToFXTradeCommand command ) {
		try {
			FXTradeBusinessDelegate.getFXTradeInstance().assignCustomer( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Customer", exc );
        }
	}

    /**
     * unassign Customer on FXTrade
     * @param		 command UnAssignCustomerFromFXTradeCommand
     */     
	@PutMapping("/unAssignCustomer")
	public void unAssignCustomer( @RequestBody(required=true)  UnAssignCustomerFromFXTradeCommand command ) {
		try {
			FXTradeBusinessDelegate.getFXTradeInstance().unAssignCustomer( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Customer", exc );
		}
	}
	
    /**
     * save Bank on FXTrade
     * @param		command AssignBankToFXTradeCommand
     */     
	@PutMapping("/assignBank")
	public void assignBank( @RequestBody AssignBankToFXTradeCommand command ) {
		try {
			FXTradeBusinessDelegate.getFXTradeInstance().assignBank( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Bank", exc );
        }
	}

    /**
     * unassign Bank on FXTrade
     * @param		 command UnAssignBankFromFXTradeCommand
     */     
	@PutMapping("/unAssignBank")
	public void unAssignBank( @RequestBody(required=true)  UnAssignBankFromFXTradeCommand command ) {
		try {
			FXTradeBusinessDelegate.getFXTradeInstance().unAssignBank( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Bank", exc );
		}
	}
	
    /**
     * save ExchangeRate on FXTrade
     * @param		command AssignExchangeRateToFXTradeCommand
     */     
	@PutMapping("/assignExchangeRate")
	public void assignExchangeRate( @RequestBody AssignExchangeRateToFXTradeCommand command ) {
		try {
			FXTradeBusinessDelegate.getFXTradeInstance().assignExchangeRate( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign ExchangeRate", exc );
        }
	}

    /**
     * unassign ExchangeRate on FXTrade
     * @param		 command UnAssignExchangeRateFromFXTradeCommand
     */     
	@PutMapping("/unAssignExchangeRate")
	public void unAssignExchangeRate( @RequestBody(required=true)  UnAssignExchangeRateFromFXTradeCommand command ) {
		try {
			FXTradeBusinessDelegate.getFXTradeInstance().unAssignExchangeRate( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign ExchangeRate", exc );
		}
	}
	
    /**
     * save SourceAccount on FXTrade
     * @param		command AssignSourceAccountToFXTradeCommand
     */     
	@PutMapping("/assignSourceAccount")
	public void assignSourceAccount( @RequestBody AssignSourceAccountToFXTradeCommand command ) {
		try {
			FXTradeBusinessDelegate.getFXTradeInstance().assignSourceAccount( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign SourceAccount", exc );
        }
	}

    /**
     * unassign SourceAccount on FXTrade
     * @param		 command UnAssignSourceAccountFromFXTradeCommand
     */     
	@PutMapping("/unAssignSourceAccount")
	public void unAssignSourceAccount( @RequestBody(required=true)  UnAssignSourceAccountFromFXTradeCommand command ) {
		try {
			FXTradeBusinessDelegate.getFXTradeInstance().unAssignSourceAccount( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign SourceAccount", exc );
		}
	}
	
    /**
     * save DestinationAccount on FXTrade
     * @param		command AssignDestinationAccountToFXTradeCommand
     */     
	@PutMapping("/assignDestinationAccount")
	public void assignDestinationAccount( @RequestBody AssignDestinationAccountToFXTradeCommand command ) {
		try {
			FXTradeBusinessDelegate.getFXTradeInstance().assignDestinationAccount( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign DestinationAccount", exc );
        }
	}

    /**
     * unassign DestinationAccount on FXTrade
     * @param		 command UnAssignDestinationAccountFromFXTradeCommand
     */     
	@PutMapping("/unAssignDestinationAccount")
	public void unAssignDestinationAccount( @RequestBody(required=true)  UnAssignDestinationAccountFromFXTradeCommand command ) {
		try {
			FXTradeBusinessDelegate.getFXTradeInstance().unAssignDestinationAccount( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign DestinationAccount", exc );
		}
	}
	
    /**
     * save Transaction on FXTrade
     * @param		command AssignTransactionToFXTradeCommand
     */     
	@PutMapping("/assignTransaction")
	public void assignTransaction( @RequestBody AssignTransactionToFXTradeCommand command ) {
		try {
			FXTradeBusinessDelegate.getFXTradeInstance().assignTransaction( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Transaction", exc );
        }
	}

    /**
     * unassign Transaction on FXTrade
     * @param		 command UnAssignTransactionFromFXTradeCommand
     */     
	@PutMapping("/unAssignTransaction")
	public void unAssignTransaction( @RequestBody(required=true)  UnAssignTransactionFromFXTradeCommand command ) {
		try {
			FXTradeBusinessDelegate.getFXTradeInstance().unAssignTransaction( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Transaction", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected FXTrade fXTrade = null;
    private static final Logger LOGGER = Logger.getLogger(FXTradeRestController.class.getName());
    
}
