/*
 * Generated by Harbormaster
 *
 *
 * Blueprint:
 * Axon4-Framework-Server
 *
 * Domain Model:
 * Banking Industry Domain Model
 *
 * Do not edit manually.
 ********************************************************
 *  Confidential
 *
 * 2026 
 * All Rights Reserved.
 *
 * This file is subject to the terms and conditions defined in
 * file 'license.txt', which is part of this source code package.
 *
 * Contributors :
 *        - General Release
 */
package com.harbormaster.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.*;
import java.util.concurrent.*;
import java.util.logging.Level;
import java.util.logging.Logger;

import com.harbormaster.api.*;
import com.harbormaster.delegate.*;
import com.harbormaster.entity.*;
import com.harbormaster.exception.*;

/**
 * RepaymentScheduleRestController as REST API
 *
 * <p>Exposes REST endpoints for the RepaymentSchedule entity.</p>
 *
 * Generated By Harbormaster
 *
 * Generated From
 *
 *      <h3>Blueprint</h3>
 * 			<table>
 *          <tr><td>name</td><td>Axon4-Framework-Server</td></tr>
 *          <tr><td>published</td><td>09/08/2026</td></tr>
 *          <tr><td>design pattern</td><td>CQRS</td></tr>
 *          <tr><td>architecture style</td><td>EventDrivenArchitecture</td></tr>
 *          </table>
 *
 *      <h3>Domain Model</h3>
 *          <table>
 *          <tr><td>name</td><td>Banking Industry Domain Model</td></tr>
 *          <tr><td>description</td><td>HCIDL model capturing core banking, payments, lending, cards, KYC, and FX capabilities.</td></tr>
 *          <tr><td>industry</td><td>Banking</td></tr>
 *          <tr><td>version</td><td>1.0.0</td></tr>
 *          <table>
 *
 * <h3>Services Used</h3>
 *
 *  	RepaymentScheduleBusinessDelegate
 *
 * <h3>Produces</h3>
 *
 *      <p>application/json</p>
 *
 * <h3>Commands Accepted</h3>
 *      <ul>
 *      <li>CreateRepaymentScheduleCommand</li>
 *      <li></li>UpdateRepaymentScheduleCommand</li>
 *      <liDeleteRepaymentScheduleCommand</li>
 *      </ul>
 *
 * <p>@author Harbormaster Dev Team</p>
 *
 */
@CrossOrigin
@RestController
@RequestMapping("/RepaymentSchedule")
public class RepaymentScheduleRestController extends BaseSpringRestController {

    /**
     * Handles create a RepaymentSchedule.  if not key provided, calls create, otherwise calls save
     * @param		RepaymentSchedule	repaymentSchedule
     * @return		CompletableFuture<UUID> 
     */
	@PostMapping("/create")
    public CompletableFuture<UUID> create( @RequestBody(required=true) CreateRepaymentScheduleCommand command ) {
		CompletableFuture<UUID> completableFuture = null;
		try {       
        	
			completableFuture = RepaymentScheduleBusinessDelegate.getRepaymentScheduleInstance().createRepaymentSchedule( command );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage(), exc );        	
        }
		
		return completableFuture;
    }

    /**
     * Handles updating a RepaymentSchedule.  if no key provided, calls create, otherwise calls save
     * @param		RepaymentSchedule repaymentSchedule
     * @return		CompletableFuture<Void>
     */
	@PutMapping("/update")
    public CompletableFuture<Void> update( @RequestBody(required=true) UpdateRepaymentScheduleCommand command ) {
		CompletableFuture<Void> completableFuture = null;
		try {                        	        
			// -----------------------------------------------
			// delegate the UpdateRepaymentScheduleCommand
			// -----------------------------------------------
			completableFuture = RepaymentScheduleBusinessDelegate.getRepaymentScheduleInstance().updateRepaymentSchedule(command);;
	    }
	    catch( Throwable exc ) {
	    	LOGGER.log( Level.WARNING, "RepaymentScheduleController:update() - successfully update RepaymentSchedule - " + exc.getMessage());        	
	    }		
		
		return completableFuture;
	}
 
    /**
     * Handles deleting a RepaymentSchedule entity
     * @param		command ${class.getDeleteCommandAlias()}
     * @return		CompletableFuture<Void>
     */
    @DeleteMapping("/delete")    
    public CompletableFuture<Void> delete( @RequestBody(required=true) DeleteRepaymentScheduleCommand command ) {                
    	CompletableFuture<Void> completableFuture = null;
    	try {
        	RepaymentScheduleBusinessDelegate delegate = RepaymentScheduleBusinessDelegate.getRepaymentScheduleInstance();

        	completableFuture = delegate.delete( command );
    		LOGGER.log( Level.WARNING, "Successfully deleted RepaymentSchedule with key " + command.getRepaymentScheduleId() );
        }
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, exc.getMessage() );
        }
        
        return completableFuture;
	}        
	
    /**
     * Handles loading a RepaymentSchedule using a UUID
     * @param		UUID uuid 
     * @return		RepaymentSchedule
     */    
    @GetMapping("/load")
    public RepaymentSchedule load( @RequestParam(required=true) UUID uuid ) {    	
    	RepaymentSchedule entity = null;

    	try {  
    		entity = RepaymentScheduleBusinessDelegate.getRepaymentScheduleInstance().getRepaymentSchedule( new RepaymentScheduleFetchOneSummary( uuid ) );   
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING, "failed to load RepaymentSchedule using Id " + uuid );
            return null;
        }

        return entity;
    }

    /**
     * Handles loading all RepaymentSchedule business objects
     * @return		Set<RepaymentSchedule>
     */
    @GetMapping("/")
    public List<RepaymentSchedule> loadAll() {                
    	List<RepaymentSchedule> repaymentScheduleList = null;
        
    	try {
            // load the RepaymentSchedule
            repaymentScheduleList = RepaymentScheduleBusinessDelegate.getRepaymentScheduleInstance().getAllRepaymentSchedule();
            
            if ( repaymentScheduleList != null )
                LOGGER.log( Level.INFO,  "successfully loaded all RepaymentSchedules" );
        }
        catch( Throwable exc ) {
            LOGGER.log( Level.WARNING,  "failed to load all RepaymentSchedules ", exc );
        	return null;
        }

        return repaymentScheduleList;
                            
    }

    /**
     * save LoanAccount on RepaymentSchedule
     * @param		command AssignLoanAccountToRepaymentScheduleCommand
     */     
	@PutMapping("/assignLoanAccount")
	public void assignLoanAccount( @RequestBody AssignLoanAccountToRepaymentScheduleCommand command ) {
		try {
			RepaymentScheduleBusinessDelegate.getRepaymentScheduleInstance().assignLoanAccount( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign LoanAccount", exc );
        }
	}

    /**
     * unassign LoanAccount on RepaymentSchedule
     * @param		 command UnAssignLoanAccountFromRepaymentScheduleCommand
     */     
	@PutMapping("/unAssignLoanAccount")
	public void unAssignLoanAccount( @RequestBody(required=true)  UnAssignLoanAccountFromRepaymentScheduleCommand command ) {
		try {
			RepaymentScheduleBusinessDelegate.getRepaymentScheduleInstance().unAssignLoanAccount( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign LoanAccount", exc );
		}
	}
	
    /**
     * save Payment on RepaymentSchedule
     * @param		command AssignPaymentToRepaymentScheduleCommand
     */     
	@PutMapping("/assignPayment")
	public void assignPayment( @RequestBody AssignPaymentToRepaymentScheduleCommand command ) {
		try {
			RepaymentScheduleBusinessDelegate.getRepaymentScheduleInstance().assignPayment( command );   
		}
        catch( Throwable exc ) {
        	LOGGER.log( Level.WARNING, "Failed to assign Payment", exc );
        }
	}

    /**
     * unassign Payment on RepaymentSchedule
     * @param		 command UnAssignPaymentFromRepaymentScheduleCommand
     */     
	@PutMapping("/unAssignPayment")
	public void unAssignPayment( @RequestBody(required=true)  UnAssignPaymentFromRepaymentScheduleCommand command ) {
		try {
			RepaymentScheduleBusinessDelegate.getRepaymentScheduleInstance().unAssignPayment( command );   
		}
		catch( Exception exc ) {
			LOGGER.log( Level.WARNING, "Failed to unassign Payment", exc );
		}
	}
	




//************************************************************************    
// Attributes
//************************************************************************
    protected RepaymentSchedule repaymentSchedule = null;
    private static final Logger LOGGER = Logger.getLogger(RepaymentScheduleRestController.class.getName());
    
}
